[api]
  enabled = true
  port = 54321
  schemas = ["public"]
  extra_search_path = ["extensions"]

[db]
  port = 54322

[studio]
  enabled = true
  port = 54323
  jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"

[functions]
  admin-create-employee = { entrypoint = "./functions/auth/admin-create-employee/index.ts" }
  password-reset = { entrypoint = "./functions/auth/password-reset/index.ts" }
  change-password = { entrypoint = "./functions/auth/change-password/index.ts" }
  admin-set-role = { entrypoint = "./functions/auth/admin-set-role/index.ts" }
  tasks = { entrypoint = "./functions/api/tasks/index.ts" }
  team = { entrypoint = "./functions/api/team/index.ts" }
  profile = { entrypoint = "./functions/api/profile/index.ts" }
